version: '3.5'

services:
  nginx:
    build: .
    environment:
      RULE_MODE: 'LINE'
      # RULE_MODE: 'BULK'
    volumes:
      - "./rules:/rules"
      - "./nginx.conf:/etc/nginx/nginx.conf"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks: []

networks: {}
