version: '3.5'

services:
  ssh:
    build: .
    environment:
      RULE_MODE: 'LINE'
      # RULE_MODE: 'BULK'
    volumes:
      - "./rules:/rules"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks: []

networks: {}
